# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# workspace
workspace: "./"

# list of dataset
dataset:
- name: dataloader_train
  batch_size: 1000
  type: DataLoader
  data_path: "{workspace}/afs"
  data_converter: "{workspace}/criteo_reader.py"

# hyper parameters of user-defined network
hyper_parameters:
  # optimizer config
  optimizer:
    class: Adam
    learning_rate: 0.0001
    strategy: async
  # user-defined <key, value> pairs
  sparse_inputs_slots: 27
  sparse_feature_number: 1000001
  sparse_feature_dim: 10
  dense_input_dim: 13
  fc_sizes: [400, 400, 400]

# select runner by name
mode: [single_train]

runner:
- name: collective_train
  class: cluster_train
  epochs: 8
  device: gpu
  fleet_mode: collective
  print_interval: 10
  phases: [phase1]
- name: ps_gpu_train
  class: cluster_train
  epochs: 8
  device: gpu
  fleet_mode: ps
  print_interval: 10
  phases: [phase1]
- name: ps_heter_train
  class: cluster_train
  epochs: 8
  device: gpu
  fleet_mode: ps-heter
  print_interval: 10
  phases: [phase1]
- name: single_train
  class: train
  epochs: 1
  device: cpu
  print_interval: 10
  phases: [phase1]


# runner will run all the phase in each epoch
phase:
- name: phase1
  model: "{workspace}/model.py" # user-defined model
  dataset_name: dataloader_train # select dataset by name
  thread_num: 2
